# Generated by Django 4.2.7 on 2023-12-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edr', '0002_alter_image_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imgfile',
            field=models.FileField(upload_to='.'),
        ),
    ]
